#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Color_Data_3._0.db {
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "colordataDb")]
	public partial class cdDb_DataContext : System.Data.Linq.DataContext {

		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

		#region Extensibility Method Definitions
		partial void OnCreated();
		partial void InsertColor(Color instance);
		partial void UpdateColor(Color instance);
		partial void DeleteColor(Color instance);
		partial void InsertDeletedColor(DeletedColor instance);
		partial void UpdateDeletedColor(DeletedColor instance);
		partial void DeleteDeletedColor(DeletedColor instance);
		partial void InsertDeletedSet(DeletedSet instance);
		partial void UpdateDeletedSet(DeletedSet instance);
		partial void DeleteDeletedSet(DeletedSet instance);
		partial void InsertDeletedSetColor(DeletedSetColor instance);
		partial void UpdateDeletedSetColor(DeletedSetColor instance);
		partial void DeleteDeletedSetColor(DeletedSetColor instance);
		partial void InsertPicture(Picture instance);
		partial void UpdatePicture(Picture instance);
		partial void DeletePicture(Picture instance);
		partial void InsertSet(Set instance);
		partial void UpdateSet(Set instance);
		partial void DeleteSet(Set instance);
		partial void InsertSetColor(SetColor instance);
		partial void UpdateSetColor(SetColor instance);
		partial void DeleteSetColor(SetColor instance);
		#endregion

		public cdDb_DataContext(string connection) :
			base(connection, mappingSource) {
			OnCreated();
		}

		public cdDb_DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
			base(connection, mappingSource) {
			OnCreated();
		}

		public System.Data.Linq.Table<Color> Colors {
			get {
				return this.GetTable<Color>();
			}
		}

		public System.Data.Linq.Table<DeletedColor> DeletedColors {
			get {
				return this.GetTable<DeletedColor>();
			}
		}

		public System.Data.Linq.Table<DeletedSet> DeletedSets {
			get {
				return this.GetTable<DeletedSet>();
			}
		}

		public System.Data.Linq.Table<DeletedSetColor> DeletedSetColors {
			get {
				return this.GetTable<DeletedSetColor>();
			}
		}

		public System.Data.Linq.Table<Picture> Pictures {
			get {
				return this.GetTable<Picture>();
			}
		}

		public System.Data.Linq.Table<Set> Sets {
			get {
				return this.GetTable<Set>();
			}
		}

		public System.Data.Linq.Table<SetColor> SetColors {
			get {
				return this.GetTable<SetColor>();
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "color")]
	public partial class Color : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Guid _Id;

		private string _Title;

		private string _Description;

		private short _R;

		private short _G;

		private short _B;

		private bool _IsUploaded;

		private EntitySet<SetColor> _SetColors;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnIdChanging(System.Guid value);
		partial void OnIdChanged();
		partial void OnTitleChanging(string value);
		partial void OnTitleChanged();
		partial void OnDescriptionChanging(string value);
		partial void OnDescriptionChanged();
		partial void OnRChanging(short value);
		partial void OnRChanged();
		partial void OnGChanging(short value);
		partial void OnGChanged();
		partial void OnBChanging(short value);
		partial void OnBChanged();
		partial void OnIsUploadedChanging(bool value);
		partial void OnIsUploadedChanged();
		#endregion

		public Color() {
			this._SetColors = new EntitySet<SetColor>(new Action<SetColor>(this.attach_SetColors), new Action<SetColor>(this.detach_SetColors));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "id", Storage = "_Id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Id {
			get {
				return this._Id;
			}
			set {
				if ((this._Id != value)) {
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "title", Storage = "_Title", DbType = "NVarChar(1024) NOT NULL", CanBeNull = false)]
		public string Title {
			get {
				return this._Title;
			}
			set {
				if ((this._Title != value)) {
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "description", Storage = "_Description", DbType = "NVarChar(1024) NOT NULL", CanBeNull = false)]
		public string Description {
			get {
				return this._Description;
			}
			set {
				if ((this._Description != value)) {
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "r", Storage = "_R", DbType = "SmallInt NOT NULL")]
		public short R {
			get {
				return this._R;
			}
			set {
				if ((this._R != value)) {
					this.OnRChanging(value);
					this.SendPropertyChanging();
					this._R = value;
					this.SendPropertyChanged("R");
					this.OnRChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "g", Storage = "_G", DbType = "SmallInt NOT NULL")]
		public short G {
			get {
				return this._G;
			}
			set {
				if ((this._G != value)) {
					this.OnGChanging(value);
					this.SendPropertyChanging();
					this._G = value;
					this.SendPropertyChanged("G");
					this.OnGChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "b", Storage = "_B", DbType = "SmallInt NOT NULL")]
		public short B {
			get {
				return this._B;
			}
			set {
				if ((this._B != value)) {
					this.OnBChanging(value);
					this.SendPropertyChanging();
					this._B = value;
					this.SendPropertyChanged("B");
					this.OnBChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "isUploaded", Storage = "_IsUploaded", DbType = "Bit NOT NULL")]
		public bool IsUploaded {
			get {
				return this._IsUploaded;
			}
			set {
				if ((this._IsUploaded != value)) {
					this.OnIsUploadedChanging(value);
					this.SendPropertyChanging();
					this._IsUploaded = value;
					this.SendPropertyChanged("IsUploaded");
					this.OnIsUploadedChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "Color_SetColor", Storage = "_SetColors", ThisKey = "Id", OtherKey = "Color_id", DeleteRule = "CASCADE")]
		public EntitySet<SetColor> SetColors {
			get {
				return this._SetColors;
			}
			set {
				this._SetColors.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_SetColors(SetColor entity) {
			this.SendPropertyChanging();
			entity.Color = this;
		}

		private void detach_SetColors(SetColor entity) {
			this.SendPropertyChanging();
			entity.Color = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "deletedColor")]
	public partial class DeletedColor : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Guid _Color_id;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnColor_idChanging(System.Guid value);
		partial void OnColor_idChanged();
		#endregion

		public DeletedColor() {
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "color_id", Storage = "_Color_id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Color_id {
			get {
				return this._Color_id;
			}
			set {
				if ((this._Color_id != value)) {
					this.OnColor_idChanging(value);
					this.SendPropertyChanging();
					this._Color_id = value;
					this.SendPropertyChanged("Color_id");
					this.OnColor_idChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "deletedSet")]
	public partial class DeletedSet : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Guid _Set_id;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnSet_idChanging(System.Guid value);
		partial void OnSet_idChanged();
		#endregion

		public DeletedSet() {
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "set_id", Storage = "_Set_id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Set_id {
			get {
				return this._Set_id;
			}
			set {
				if ((this._Set_id != value)) {
					this.OnSet_idChanging(value);
					this.SendPropertyChanging();
					this._Set_id = value;
					this.SendPropertyChanged("Set_id");
					this.OnSet_idChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "deletedSetColor")]
	public partial class DeletedSetColor : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Guid _Set_id;

		private System.Guid _Color_id;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnSet_idChanging(System.Guid value);
		partial void OnSet_idChanged();
		partial void OnColor_idChanging(System.Guid value);
		partial void OnColor_idChanged();
		#endregion

		public DeletedSetColor() {
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "set_id", Storage = "_Set_id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Set_id {
			get {
				return this._Set_id;
			}
			set {
				if ((this._Set_id != value)) {
					this.OnSet_idChanging(value);
					this.SendPropertyChanging();
					this._Set_id = value;
					this.SendPropertyChanged("Set_id");
					this.OnSet_idChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "color_id", Storage = "_Color_id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Color_id {
			get {
				return this._Color_id;
			}
			set {
				if ((this._Color_id != value)) {
					this.OnColor_idChanging(value);
					this.SendPropertyChanging();
					this._Color_id = value;
					this.SendPropertyChanged("Color_id");
					this.OnColor_idChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "picture")]
	public partial class Picture : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private int _Id;

		private System.Data.Linq.Binary _Img;

		private System.Guid _Set_id;

		private bool _IsUploaded;

		private EntityRef<Set> _Set;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnIdChanging(int value);
		partial void OnIdChanged();
		partial void OnImgChanging(System.Data.Linq.Binary value);
		partial void OnImgChanged();
		partial void OnSet_idChanging(System.Guid value);
		partial void OnSet_idChanged();
		partial void OnIsUploadedChanging(bool value);
		partial void OnIsUploadedChanged();
		#endregion

		public Picture() {
			this._Set = default(EntityRef<Set>);
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "id", Storage = "_Id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public int Id {
			get {
				return this._Id;
			}
			set {
				if ((this._Id != value)) {
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "img", Storage = "_Img", DbType = "Image NOT NULL", CanBeNull = false, UpdateCheck = UpdateCheck.Never)]
		public System.Data.Linq.Binary Img {
			get {
				return this._Img;
			}
			set {
				if ((this._Img != value)) {
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "set_id", Storage = "_Set_id", DbType = "UniqueIdentifier NOT NULL")]
		public System.Guid Set_id {
			get {
				return this._Set_id;
			}
			set {
				if ((this._Set_id != value)) {
					this.OnSet_idChanging(value);
					this.SendPropertyChanging();
					this._Set_id = value;
					this.SendPropertyChanged("Set_id");
					this.OnSet_idChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "isUploaded", Storage = "_IsUploaded", DbType = "Bit NOT NULL")]
		public bool IsUploaded {
			get {
				return this._IsUploaded;
			}
			set {
				if ((this._IsUploaded != value)) {
					this.OnIsUploadedChanging(value);
					this.SendPropertyChanging();
					this._IsUploaded = value;
					this.SendPropertyChanged("IsUploaded");
					this.OnIsUploadedChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "Set_Picture", Storage = "_Set", ThisKey = "Set_id", OtherKey = "Id", IsForeignKey = true, DeleteOnNull = true)]
		public Set Set {
			get {
				return this._Set.Entity;
			}
			set {
				Set previousValue = this._Set.Entity;
				if (((previousValue != value)
							|| (this._Set.HasLoadedOrAssignedValue == false))) {
					this.SendPropertyChanging();
					if ((previousValue != null)) {
						this._Set.Entity = null;
						previousValue.Pictures.Remove(this);
					}
					this._Set.Entity = value;
					if ((value != null)) {
						value.Pictures.Add(this);
						this._Set_id = value.Id;
					}
					else {
						this._Set_id = default(System.Guid);
					}
					this.SendPropertyChanged("Set");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "set")]
	public partial class Set : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Guid _Id;

		private string _Title;

		private string _Description;

		private System.DateTime _DateCreated;

		private System.DateTime _LastUpdated;

		private bool _Snap;

		private bool _IsUploaded;

		private EntitySet<Picture> _Pictures;

		private EntitySet<SetColor> _SetColors;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnIdChanging(System.Guid value);
		partial void OnIdChanged();
		partial void OnTitleChanging(string value);
		partial void OnTitleChanged();
		partial void OnDescriptionChanging(string value);
		partial void OnDescriptionChanged();
		partial void OnDateCreatedChanging(System.DateTime value);
		partial void OnDateCreatedChanged();
		partial void OnLastUpdatedChanging(System.DateTime value);
		partial void OnLastUpdatedChanged();
		partial void OnSnapChanging(bool value);
		partial void OnSnapChanged();
		partial void OnIsUploadedChanging(bool value);
		partial void OnIsUploadedChanged();
		#endregion

		public Set() {
			this._Pictures = new EntitySet<Picture>(new Action<Picture>(this.attach_Pictures), new Action<Picture>(this.detach_Pictures));
			this._SetColors = new EntitySet<SetColor>(new Action<SetColor>(this.attach_SetColors), new Action<SetColor>(this.detach_SetColors));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "id", Storage = "_Id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Id {
			get {
				return this._Id;
			}
			set {
				if ((this._Id != value)) {
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "title", Storage = "_Title", DbType = "NVarChar(1024) NOT NULL", CanBeNull = false)]
		public string Title {
			get {
				return this._Title;
			}
			set {
				if ((this._Title != value)) {
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "description", Storage = "_Description", DbType = "NVarChar(1024) NOT NULL", CanBeNull = false)]
		public string Description {
			get {
				return this._Description;
			}
			set {
				if ((this._Description != value)) {
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "dateCreated", Storage = "_DateCreated", DbType = "DateTime NOT NULL")]
		public System.DateTime DateCreated {
			get {
				return this._DateCreated;
			}
			set {
				if ((this._DateCreated != value)) {
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "lastUpdated", Storage = "_LastUpdated", DbType = "DateTime NOT NULL")]
		public System.DateTime LastUpdated {
			get {
				return this._LastUpdated;
			}
			set {
				if ((this._LastUpdated != value)) {
					this.OnLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._LastUpdated = value;
					this.SendPropertyChanged("LastUpdated");
					this.OnLastUpdatedChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "snap", Storage = "_Snap", DbType = "Bit NOT NULL")]
		public bool Snap {
			get {
				return this._Snap;
			}
			set {
				if ((this._Snap != value)) {
					this.OnSnapChanging(value);
					this.SendPropertyChanging();
					this._Snap = value;
					this.SendPropertyChanged("Snap");
					this.OnSnapChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "isUploaded", Storage = "_IsUploaded", DbType = "Bit NOT NULL")]
		public bool IsUploaded {
			get {
				return this._IsUploaded;
			}
			set {
				if ((this._IsUploaded != value)) {
					this.OnIsUploadedChanging(value);
					this.SendPropertyChanging();
					this._IsUploaded = value;
					this.SendPropertyChanged("IsUploaded");
					this.OnIsUploadedChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "Set_Picture", Storage = "_Pictures", ThisKey = "Id", OtherKey = "Set_id", DeleteRule = "CASCADE")]
		public EntitySet<Picture> Pictures {
			get {
				return this._Pictures;
			}
			set {
				this._Pictures.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "Set_SetColor", Storage = "_SetColors", ThisKey = "Id", OtherKey = "Set_id", DeleteRule = "CASCADE")]
		public EntitySet<SetColor> SetColors {
			get {
				return this._SetColors;
			}
			set {
				this._SetColors.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_Pictures(Picture entity) {
			this.SendPropertyChanging();
			entity.Set = this;
		}

		private void detach_Pictures(Picture entity) {
			this.SendPropertyChanging();
			entity.Set = null;
		}

		private void attach_SetColors(SetColor entity) {
			this.SendPropertyChanging();
			entity.Set = this;
		}

		private void detach_SetColors(SetColor entity) {
			this.SendPropertyChanging();
			entity.Set = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "setColor")]
	public partial class SetColor : INotifyPropertyChanging, INotifyPropertyChanged {

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private System.Guid _Set_id;

		private System.Guid _Color_id;

		private double _X;

		private double _Y;

		private short _Position;

		private int _Z;

		private int _IconSize;

		private bool _IsUploaded;

		private EntityRef<Color> _Color;

		private EntityRef<Set> _Set;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnSet_idChanging(System.Guid value);
		partial void OnSet_idChanged();
		partial void OnColor_idChanging(System.Guid value);
		partial void OnColor_idChanged();
		partial void OnXChanging(double value);
		partial void OnXChanged();
		partial void OnYChanging(double value);
		partial void OnYChanged();
		partial void OnPositionChanging(short value);
		partial void OnPositionChanged();
		partial void OnZChanging(int value);
		partial void OnZChanged();
		partial void OnIconSizeChanging(int value);
		partial void OnIconSizeChanged();
		partial void OnIsUploadedChanging(bool value);
		partial void OnIsUploadedChanged();
		#endregion

		public SetColor() {
			this._Color = default(EntityRef<Color>);
			this._Set = default(EntityRef<Set>);
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "set_id", Storage = "_Set_id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Set_id {
			get {
				return this._Set_id;
			}
			set {
				if ((this._Set_id != value)) {
					this.OnSet_idChanging(value);
					this.SendPropertyChanging();
					this._Set_id = value;
					this.SendPropertyChanged("Set_id");
					this.OnSet_idChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "color_id", Storage = "_Color_id", DbType = "UniqueIdentifier NOT NULL", IsPrimaryKey = true)]
		public System.Guid Color_id {
			get {
				return this._Color_id;
			}
			set {
				if ((this._Color_id != value)) {
					this.OnColor_idChanging(value);
					this.SendPropertyChanging();
					this._Color_id = value;
					this.SendPropertyChanged("Color_id");
					this.OnColor_idChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "x", Storage = "_X", DbType = "Float NOT NULL")]
		public double X {
			get {
				return this._X;
			}
			set {
				if ((this._X != value)) {
					this.OnXChanging(value);
					this.SendPropertyChanging();
					this._X = value;
					this.SendPropertyChanged("X");
					this.OnXChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "y", Storage = "_Y", DbType = "Float NOT NULL")]
		public double Y {
			get {
				return this._Y;
			}
			set {
				if ((this._Y != value)) {
					this.OnYChanging(value);
					this.SendPropertyChanging();
					this._Y = value;
					this.SendPropertyChanged("Y");
					this.OnYChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "position", Storage = "_Position", DbType = "SmallInt NOT NULL")]
		public short Position {
			get {
				return this._Position;
			}
			set {
				if ((this._Position != value)) {
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "z", Storage = "_Z", DbType = "Int NOT NULL")]
		public int Z {
			get {
				return this._Z;
			}
			set {
				if ((this._Z != value)) {
					this.OnZChanging(value);
					this.SendPropertyChanging();
					this._Z = value;
					this.SendPropertyChanged("Z");
					this.OnZChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IconSize", DbType = "Int NOT NULL")]
		public int IconSize {
			get {
				return this._IconSize;
			}
			set {
				if ((this._IconSize != value)) {
					this.OnIconSizeChanging(value);
					this.SendPropertyChanging();
					this._IconSize = value;
					this.SendPropertyChanged("IconSize");
					this.OnIconSizeChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Name = "isUploaded", Storage = "_IsUploaded", DbType = "Bit NOT NULL")]
		public bool IsUploaded {
			get {
				return this._IsUploaded;
			}
			set {
				if ((this._IsUploaded != value)) {
					this.OnIsUploadedChanging(value);
					this.SendPropertyChanging();
					this._IsUploaded = value;
					this.SendPropertyChanged("IsUploaded");
					this.OnIsUploadedChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "Color_SetColor", Storage = "_Color", ThisKey = "Color_id", OtherKey = "Id", IsForeignKey = true, DeleteOnNull = true)]
		public Color Color {
			get {
				return this._Color.Entity;
			}
			set {
				Color previousValue = this._Color.Entity;
				if (((previousValue != value)
							|| (this._Color.HasLoadedOrAssignedValue == false))) {
					this.SendPropertyChanging();
					if ((previousValue != null)) {
						this._Color.Entity = null;
						previousValue.SetColors.Remove(this);
					}
					this._Color.Entity = value;
					if ((value != null)) {
						value.SetColors.Add(this);
						this._Color_id = value.Id;
					}
					else {
						this._Color_id = default(System.Guid);
					}
					this.SendPropertyChanged("Color");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "Set_SetColor", Storage = "_Set", ThisKey = "Set_id", OtherKey = "Id", IsForeignKey = true, DeleteOnNull = true)]
		public Set Set {
			get {
				return this._Set.Entity;
			}
			set {
				Set previousValue = this._Set.Entity;
				if (((previousValue != value)
							|| (this._Set.HasLoadedOrAssignedValue == false))) {
					this.SendPropertyChanging();
					if ((previousValue != null)) {
						this._Set.Entity = null;
						previousValue.SetColors.Remove(this);
					}
					this._Set.Entity = value;
					if ((value != null)) {
						value.SetColors.Add(this);
						this._Set_id = value.Id;
					}
					else {
						this._Set_id = default(System.Guid);
					}
					this.SendPropertyChanged("Set");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging() {
			if ((this.PropertyChanging != null)) {
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName) {
			if ((this.PropertyChanged != null)) {
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
